

Capabilities:
  Application: &ApplicationCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Channel: &ChannelCapabilities
    V2_0: true

# ORGANIZATIONS
Organizations:

  - &Orderer
    Name: OrdererMSP
    SkipAsForeign: false
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/orderer.com/msp
    Policies: &OrdererPolicies
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

  - &Org1
    Name: Org1
    ID: Org1MSP
    MSPDir: ./crypto-config/peerOrganizations/Org1.com/msp
    Policies: &Org1Policies
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
    AnchorPeers:
      - Host: peer0.Org1.com
        Port: 7051

# ORDERER
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - localhost:7050
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Capabilities:
     <<: *OrdererCapabilities


# APPLICATION
Application: &ApplicationDefaults
  Policies: &ApplicationDefaultPolicies
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ApplicationCapabilities

  Organizations:

# CHANNEL
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

# PROFILES
Profiles:

  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
          - <<: *Orderer
    Consortiums:
      SampleConsortium:
        Organizations:
          - <<: *Org1

  Channel:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Application:
        <<: *ApplicationDefaults
        Organizations:
         - <<: *Org1
